<?php

return [

    'profilePicPath' => 'uploads/profilePic/',
    'postsPath' => 'uploads/posts/',
    'PaginationPageSize' => '8',
    'NoPostsExist' => '-1',
    'userDisplayCount' => '5',
    'placeIndex' => '2',
    'firstIndex' => '0',
    'redirectURL' => '/home',
    'redirectURLName' => 'home',
    'redirectTime' => '5',
    'month1' => 'Jan',
    'month2' => 'Feb',
    'month3' => 'Mar',
    'month4' => 'Apr',
    'month5' => 'May',
    'month6' => 'Jun',
    'month7' => 'Jul',
    'month8' => 'Aug',
    'month9' => 'Sep',
    'month10' => 'Oct',
    'month11' => 'Nov',
    'month12' => 'Dec',
    'confirmMail' => 'Please verify account using the email send to the your account.',
    'loginVerified' => 'Login using the credentials provided during registration',
    'editSuccess' => 'Profile edited successfully.',
    'noUser' => 'The user you are searching doesn\'t exist',
    'noPost' => 'The post you are searching doesn\'t exist',
];